version: '2'
services:
  gateway:
    build: gateway/.
    ports:
      - "3012:3012"
    volumes:
      - ${PWD}/gateway/.env:/var/BUGOUT/gateway/.env
    environment:
      - BROKERS
  reverse-proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/Caddyfile:/etc/Caddyfile
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/.caddy:/root/.caddy
  kafkacat:
    build: kafkacat/.
