version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - /mnt/stateful_partition/BUGOUT/redis:/data:z
    privileged: true
    command: /bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo 65535 > /proc/sys/net/core/somaxconn ; redis-server'
  gateway:
    build: gateway/.
    volumes:
      - "./gateway/.env:/BUGOUT/.env:z"
    links:
      - "redis"
    depends_on:
      - "redis"
    ports:
      - "33012:3012" # for local dev
  micro-judge:
    build: micro-judge/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-changelog:
    build: micro-changelog/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-color-chooser:
    build: micro-color-chooser/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-game-lobby:
    build: micro-game-lobby/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-sync:
    build: micro-sync/.
    links:
      - "redis"
    depends_on:
      - "redis"
  botlink:
    build: botlink/.
    depends_on:
      - "redis"
    volumes:
      - "./botlink/.env:/BUGOUT/.env:z"
  undo:
    build: undo/.
    links:
      - "redis"
    depends_on:
      - "redis"
  reverse-proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "botlink"
      - "gateway"
    volumes:
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/Caddyfile:/etc/Caddyfile:z
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/.caddy:/root/.caddy:z
