# This file is for local development only.
# To see the cloud configs, look at dc-giant.yml
# and dc-tiny.yml

version: '3.3'
services:
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - /mnt/stateful_partition/BUGOUT/redis:/data
    command: /bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo 65535 > /proc/sys/net/core/somaxconn ; redis-server'
  gateway:
    build: gateway/.
    ports:
      - "3012:3012"
    volumes:
      - ${PWD}/gateway/.env:/var/BUGOUT/gateway/.env
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-judge:
    build: micro-judge/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-changelog:
    build: micro-changelog/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-color-chooser:
    build: micro-color-chooser/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-game-lobby:
    build: micro-game-lobby/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-sync:
    build: micro-sync/.
    links:
      - "redis"
    depends_on:
      - "redis"
  botlink:
    build: botlink/.
    depends_on:
      - "redis"
    volumes:
      - "./botlink/.env:/var/BUGOUT/botlink/.env"
  reverse-proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "botlink"
      - "gateway"
    volumes:
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/Caddyfile:/etc/Caddyfile
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/.caddy:/root/.caddy
