# This file is for local development only.
# To see the cloud configs, look at dc-giant.yml
# and dc-tiny.yml

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "bugout-move-accepted-ev:1:1,bugout-move-made-ev:1:1,bugout-move-rejected-ev:1:1,bugout-make-move-cmd:1:1,bugout-game-states:1:1,bugout-provide-history-cmd:1:1,bugout-history-provided-ev:1:1,bugout-find-public-game-cmd:1:1,bugout-create-game-cmd:1:1,bugout-wait-for-opponent-ev:1:1,bugout-game-ready-ev:1:1,bugout-private-game-rejected-ev:1:1,bugout-join-private-game-cmd:1:1,bugout-game-lobby-commands:1:1,bugout-game-lobby:1:1,bugout-choose-color-pref-cmd:1:1,bugout-session-game-ready-ev:1:1,bugout-game-color-pref-ev:1:1,bugout-colors-chosen-ev:1:1,bugout-client-heartbeat-ev:1:1,bugout-shutdown-ev:1:1,bugout-session-disconnected-ev:1:1,bugout-quit-game-cmd:1:1,bugout-public-game-aggregate-store:1:1,bugout-game-participation-ev:1:1,bugout-client-participation-ev:1:1,bugout-consecutive-pass-store:1:1,bugout-req-sync-cmd:1:1,bugout-sync-reply-ev:1:1,bugout-make-move-cmd-dedup:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - /mnt/stateful_partition/BUGOUT/redis:/data
    command: /bin/bash -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo 65535 > /proc/sys/net/core/somaxconn ; redis-server'
  gateway:
    build: gateway/.
    ports:
      - "3012:3012"
    volumes:
      - ${PWD}/gateway/.env:/var/BUGOUT/gateway/.env
    links:
      - "kafka"
    depends_on:
      - "kafka"
    environment:
      - BROKERS
  bugle:
    build: bugle/.
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ${PWD}/bugle/.env:/var/BUGOUT/bugle/.env
    environment:
      - DELAY_SECS
      - AWS_REGION
      - DISABLED
      - TAG_NAME
  judge:
    build: judge/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  changelog:
    build: changelog/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  history-provider:
    build: history-provider/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  game-lobby:
    build: game-lobby/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  color-chooser:
    build: color-chooser/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  participation:
    build: participation/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  sync:
    build: sync/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  startup:
    build: startup/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
  reaper:
    build: reaper/.
    links:
      - "kafka"
    depends_on:
      - "kafka"
    volumes:
      - "./reaper/.env:/var/BUGOUT/reaper/.env"
    environment:
      - ALLOWED_IDLE_SECS
      - AWS_REGION
      - DISABLED
      - STARTUP_GRACE_SECS
      - TAG_NAME
  kafkacat:
    build: kafkacat/.
    links:
      - "kafka"
  micro-judge:
    build: micro-judge/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-changelog:
    build: micro-changelog/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-color-chooser:
    build: micro-color-chooser/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-game-lobby:
    build: micro-game-lobby/.
    links:
      - "redis"
    depends_on:
      - "redis"
  micro-sync:
    build: micro-sync/.
    links:
      - "redis"
    depends_on:
      - "redis"
  botlink:
    build: botlink/.
    depends_on:
      - "redis"
    volumes:
      - "./botlink/.env:/var/BUGOUT/botlink/.env"
  reverse-proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "botlink"
      - "gateway"
    volumes:
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/Caddyfile:/etc/Caddyfile
      - /mnt/stateful_partition/BUGOUT/reverse-proxy/.caddy:/root/.caddy
