[package]
name = "redis_conn_pool"
version = "0.1.1"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
redis = { version = "0.16.0", features = ["r2d2"] }
