[package]
name = "redis_conn_pool"
version = "0.1.1"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
redis = "0.16.0"
r2d2_redis = { git = "https://github.com/Terkwood/r2d2-redis", branch = "tinker" }
