[package]
name = "micro_judge"
version = "0.1.5"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["serde", "v4"] }
bincode = "1.2.1"
micro_model_moves = { git = "https://github.com/Terkwood/BUGOUT", branch = "unstable" }
redis_conn_pool = { git = "https://github.com/Terkwood/BUGOUT", branch = "unstable" }
