[package]
name = "tinybrain"
version = "0.1.0"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
micro_model_moves = { git = "https://github.com/Terkwood/BUGOUT", branch = "unstable" }
