[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "core-model"
version = "0.2.0"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
