[package]
name = "micro_changelog"
version = "0.1.0"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"


[dependencies]
redis = "0.15.1"
r2d2_redis = "0.13.0"
micro_model_moves = { path = "../micro-model/moves" }
redis_conn_pool = { path = "../redis-conn-pool" }
