[package]
name = "micro_changelog"
version = "0.0.0"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"


[dependencies]
micro_model_moves = { path = "../micro-model/moves" }
redis_conn_pool = { path = "../redis-conn-pool" }
