[package]
name = "micro_changelog"
version = "0.1.3"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"


[dependencies]
micro_model_moves = { git = "https://github.com/Terkwood/BUGOUT", branch = "unstable" }
redis_conn_pool = { git = "https://github.com/Terkwood/BUGOUT", branch = "unstable" }
#### TODO
##TODO
# TODO
####TODO
redis_streams = { git = "https://github.com/Terkwood/BUGOUT", branch = "fix/dedupe-entry-ids" }
bincode = "1.2.1"
uuid = { version = "0.8.1", features = ["serde"] }
log = "0.4.8"
env_logger = "0.7.1"
