use super::topics;
use crate::repo::AllEntryIds;
use log::{trace, warn};
use redis_conn_pool::redis;
use redis_conn_pool::Pool;
use redis_streams::XReadEntryId;
use std::collections::HashMap;
use std::str::FromStr;
use std::sync::Arc;
use uuid::Uuid;
