[package]
name = "redis_streams"
version = "0.3.0"
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["serde","v4"] }
redis = "0.16.0"
