[package]
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "redis_streams"
version = "1.0.0"

[dependencies]
anyhow = "1.0.40"
redis = "0.20.1"
uuid = {version = "0.8.2", features = ["serde", "v4"]}
