[package]
authors = ["terkwood <38859656+Terkwood@users.noreply.github.com>"]
edition = "2018"
name = "redis_streams"
version = "0.4.0"

[dependencies]
uuid = {version = "0.8.1", features = ["serde", "v4"]}
